[build]
builder = "Dockerfile"

[deploy]
startCommand = "gunicorn jhs.wsgi:application --bind 0.0.0.0:8000 --workers 3"

[network]
# Django internal by default
internal = true
external = false

# Allow ONLY /mpesa/callback to be public
[[redirects]]
from = "/mpesa/callback/*"
to = "/mpesa/callback/:splat"
status = 200
service = "django"
internal = false
