# Generated by Django 5.2.5 on 2025-08-17 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('success', 'success'), ('failed', 'failed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
